**1. Variables Basicas** 

Una variable es un nombre al que se le asigna un valor.

Puedes usar números y letras, pero debe comenzar con una letra.

Hace diferencia entre minúsculas y minusculas.

Tratar de evitar el uso de "tildes" y "ñ"

In [ ]:
print ("Hola Mundo")

print (3+6) #Suma
print (7-3) #Resta
print (2*3) #Multiplicación
print (4/2) #División
print (2**5) #Exponencial
print (10%5) #Residuo

a = 10-3
b= 3+5
print (a*b)

c="letra"
print (c)

d="David"
e="Antonio"
f="Estudiante"
print("Hola, mi nombre es {}, mi apellido es {} y soy {}".format(d,e,f))

Hola Mundo
9
4
6
2.0
32
0
56
letra
Hola, mi nombre es David, mi apellido es Antonio y soy Estudiante


**2. Tipos de Datos**

Tipos:            str,            int,              float.

Clase:           Texto,      numero entero,      numero real.

Ejemplo:      "Solo texto",       20,               20.3.

In [ ]:
a=12

#La variable "a" tiene el valor de doce

'''De esta forma puedo comentar a manera
de parrafos'''

a+12

print (str("David Antonio González Gómez"))
print (int(12.4))
print (float(5.985))

#Convertir un dato a otro tipo de dato (CASTING)
x=34.6
print(int(x))

print (bool("")) #Una lista vacia se toma como falso
print (bool(0)) #Cualquier valor diferente de cero, dará TRUE
print (bool("Hola")) #Una lista vacia se toma como Verdadero

David Antonio González Gómez
12
5.985
34
False
False
True


**3. Ingresar Variables** 

Asignar Valores a una variable de forma que se le pregunte al ejecutor.

No olvidar cambiar el valor ingresado, porque tiene valor de string y NO se puede manipular

In [ ]:
a = input('Ingrese un numero: ') #OJO la variable se registra como string.
a = int(a) #Entonces, tenemos que convertirlo a valor numerico ENTERO
print ("La numero ingresado es: ", a)
print ("x + 8 = ", a+8)

Ingrese un numero: 8
La numero ingresado es:  8
a + 8 =  16


**4. Operadores** 

Calcularemos el área de un triangulo para aprender los operadores básicos.

También el promedio de las distintas notas.

In [ ]:
# Hallar el área de un triangulo
''' 
DATOS: 
B = Base
H = Altura
Area = (Base * Altura) / 2
'''
B = float (input('Ingrese la base: '))
H = float (input('Ingrese la altura: '))
A = (B*H)/2
print("El resultado del area del triangulo es: ", A)

Ingrese la base: 10.5
Ingrese la altura: 12.5
El área es:  65.625


In [ ]:
# Hallar el promedio de tres notas
''' 
DATOS: 
N1 = Nota 1
N2 = Nota 2
N3 = Nota 3
P = Promedio
'''
N1 = float(input('Ingrese la nota 1: '))
N2 = float(input('Ingrese la nota 2: '))
N3 = float(input('Ingrese la nota 3: '))
P = (N1 + N2 + N3)/3
print("El promedio de las notas es: ", P)

Ingrese la nota 1: 10
Ingrese la nota 2: 9
Ingrese la nota 3: 8
El promedio de las notas es:  9.0


**5. Operadores Relacionales** 

Valores de comparación que distingue dos valores de los cuales obtiene un resultado VERDADERO o FALSO

In [ ]:
print (4 > 2)
print (2 < 10)
print (4 == 4)
print (5 >= 5)
print (9 != 3)

True
True
True
True
True


In [ ]:
print (5 > 5)
print (2 >= 3)
print (12 == 5)
print (5 < 3)
print (10 != 10)

False
False
False
False
False


**6. Operadores Logicos** 

Se implementan las compueras logicas: AND, OR  y NOT

In [ ]:
print ("Compuerta AND")
print (False and False)
print (False and True)
print (True and False)
print (True and True)

print ("Compuerta OR")
print (False or False)
print (False or True)
print (True or False)
print (True or True)

print ("Compuerta NOT")
print (not True)
print (not False)

Compuerta AND
False
False
False
True
Compuerta OR
False
True
True
True
Compuerta NOT
False
True


In [ ]:
print (not(False and False))

True


**7. Condicionales IF / ELSE** 

El condicional IF es un espacio para tomar decisiones que actua dependiendo el estado VERDADERO o FALSO

ELIF: Permite encadenar los Else e IF de manera seguida, permitiendo un mayor legibilidad de las estucturas anidadas.

In [ ]:
# Numero Positivo o Negativo

A = float(input('Ingrese un numero: '))

if A>0:
  print ("El valor ingresado es Positivo")
else:
  print ("El valor ingresado es Negativo")

Ingrese un numero: -2
El valor ingresado es Negativo


In [ ]:
# Numero Positivo / Neutro / Negativo

B = float(input('Ingrese un numero: '))

if B<0:
  print ("El valor ingresado es Negativo")
elif B==0:
  print ("El valor ingresado es Neutro")
else: 
  print ("El valor ingresado es Positivo")

Ingrese un numero: 0
El valor ingresado es Neutro


In [ ]:
# Hallar el mayor de dos numeros
''' 
DATOS: 
A = Valor del primer numero
B = Valor del segundo numero
'''

A = float(input('Ingrese el valor de A: '))
B = float(input('Ingrese el valor de B: '))

if A>B:
  print ("El valor A es mayor que B")
else:
  print ("El valor B es mayor que A")

Ingrese el valor de A: 8
Ingrese el valor de B: 4
El valor A es mayor que B


In [ ]:
# Hallar numero par o impar
''' 
DATOS: 
N = Número
'''

N = float(input('Ingrese un numero: '))

if (N%2)==0:
  print ("El Numero {} es un numero par".format(N))
else:
  print ("El Numero {} es un numero impar".format(N))

Ingrese un numero: 15
El Numero 15.0 es un numero impar


In [ ]:
# Calificacion de notas
''' 
DATOS: 
N = Nota
R = Respuesta
'''

N = float(input('Ingrese una nota: '))

if N<59:
  print ("Reprobado")
elif N<=79:
  print ("Arobado")
elif N<=89:
  print ("Sobresaliente")
else: 
  print ("Excelente")

Ingrese una nota: 25
Reprobado


**8. Estructuras Iterativas FOR / WHILE** 

Muchas veces, es necesario repetir una instrucción ya que así lo requiere el algoritmo. Para no repetir el codigo más de una vez, en estos casos usaremos la instrucción ciclo.

WHILE: El bloque de la secuencia de instrucciones se repite siempre que la condicion dada por el valor de una variable (Si la expresion logica es verdadera)

FOR: Se caracteriza por repetirse un numero determinado de veces.

In [ ]:
#Suma de los números del 1 al 6

N = 6
Suma = 0
i = 1

while i <= N:
  Suma = Suma + i
  i = i + 1
  print ("La suma de los numeros hasta ", N, "es: ", Suma)
print ("\nLa suma de los numeros hasta ", N, "es: ", Suma)

La suma de los numeros hasta  6 es:  1
La suma de los numeros hasta  6 es:  3
La suma de los numeros hasta  6 es:  6
La suma de los numeros hasta  6 es:  10
La suma de los numeros hasta  6 es:  15
La suma de los numeros hasta  6 es:  21

La suma de los numeros hasta  6 es:  21


In [ ]:
# Mostrar los resultados de una tabla de multiplicación

N = int(input('Introduce la tabla que desea ver: '))
Max = 10
i = 1

while i <= Max:
  print (i, " x ", N, "= ", (N * i))
  i = i + 1

Introduce la tabla que desea ver: 9
1  x  9 =  9
2  x  9 =  18
3  x  9 =  27
4  x  9 =  36
5  x  9 =  45
6  x  9 =  54
7  x  9 =  63
8  x  9 =  72
9  x  9 =  81
10  x  9 =  90


In [ ]:
# Ingrese los N numeros de forma ascendiente

N = int(input('Introduce la tabla que desea ver: '))
i = 1

while i <= N:
  print (i)
  i = i + 1

Introduce la tabla que desea ver: 7
1
2
3
4
5
6
7


In [ ]:
# Ingrese los N numeros de forma descendiente

N = int(input('Introduce la tabla que desea ver: '))
i = N

while i >= 1:
  print (i)
  i = i - 1

Introduce la tabla que desea ver: 9
9
8
7
6
5
4
3
2
1


In [ ]:
for i in "Numero":
  print (i)

N
u
m
e
r
o


In [ ]:
#Calcular el numero de vocales en una frase

F = str (input("Ingrese una frase: "))
Vocales = 'aeiouAEIOU'
Contador = 0

for i in F:
  if i in Vocales:
    Contador = Contador + 1

print ("El numero de vocales es: ", Contador)

Ingrese una frase: Hola Mundo
El numero de vocales es:  4


In [ ]:
#Tabla de Multiplicar del 1 al 10

N = int(input("Ingrese un Número: "))

for i in range(1, 11):
  print (N, " x ", i, " = ", (N*i))

Ingrese un Número: 9
9  x  1  =  9
9  x  2  =  18
9  x  3  =  27
9  x  4  =  36
9  x  5  =  45
9  x  6  =  54
9  x  7  =  63
9  x  8  =  72
9  x  9  =  81
9  x  10  =  90


In [ ]:
# Mayor que el anterior

Valor = int(input("¿Cuantos valores va a introducir? "))

if Valor < 1:
  print ("Error")
else: 
  primero = int(input("Escriba un numero: "))

  for i in range(Valor - 1):
    numero = int(input(f"Escriba un valor más grande que {primero}: "))
    if numero <= primero:
      print (f"{numero} no es mayor que {primero}")
  print ("FIN")

¿Cuantos valores va a introducir? 6
Escriba un numero: 5
Escriba un valor más grande que 5: 4
4 no es mayor que 5
Escriba un valor más grande que 5: 6
Escriba un valor más grande que 5: 6
Escriba un valor más grande que 5: 10
Escriba un valor más grande que 5: 8
FIN


In [ ]:
# Mostrar los n primeros numeros de forma descendiente

N = int(input("Escriba un numero: "))

for i in range (N, 0, -1):
  print (i)

Escriba un numero: 8
8
7
6
5
4
3
2
1


In [ ]:
# Suma de los primeros N numeros

N = int(input("Escriba un numero: "))
Suma = 0

for i in range (1, N+1):
  Suma = Suma + i
  print (Suma)

Escriba un numero: 5
1
3
6
10
15


In [ ]:
#Calcular el factorial de un número
#Ejemplo: 3! = 3*2*1 = 6

N = int(input("Escriba un numero: "))

if N<=0:
  print ("Escriba un valor positivo")
else:
  Fact = 1
  for i in range (1, N+1):
    Fact = Fact * i
  print (Fact)

Escriba un numero: 5
120


**9. Series** 

Secuencia de números



In [ ]:
# Generar los multiplos de 3

N = int(input("Escriba un numero: "))

if N<=0:
  print ("Escriba un valor positivo")
else:
  m = 3
  for i in range (1, N+1):
    print(m)
    m = m + 3

Escriba un numero: 3
3
6
9


In [ ]:
# Serie 4,3,2,1,4,3,2,1,4,3,2,1...
# c = controlador
# w = interruptor

N = int(input("Escriba un numero: "))

if N<=0:
  print ("Escriba un valor positivo")
else:
  c = 0
  w = 4
  for i in range (N+1, 1, -1):
    print((i-1), end=",")

Escriba un numero: 4
4,3,2,1,

**10. Listas** 

Tipo de dato en python con caracteristicas especiales, Nos permiten almacenar cualquier tipo de valor como enteros, cadenas y hasta otras funciones.

In [ ]:
A = [1, 2, 3, 4]
B = ["Python", 100, 'Java', 2.4]

print (A)
print (B)

[1, 2, 3, 4]
['Python', 100, 'Java', 2.4]


In [ ]:
B[2]

'Java'

In [ ]:
A+B

[1, 2, 3, 4, 'Python', 100, 'Java', 2.4]

In [ ]:
A = [1, 2, 3, 4]
B = [10, 12, 13, 14]
C = [40, 50, 90]

L = [B, A, C]
L

[[10, 12, 13, 14], [1, 2, 3, 4], [40, 50, 90]]

In [ ]:
# BUSCAR POR FILAS Y COLUMNAS
L[2][2]

90

**11. Break / Continue** 

La instrucción continue se usa dentro de un ciclo FOR asociado a un ciclo SI y no ejecuta la linea de código.

In [ ]:
# Identificar pares e impares

N1 = int(input("Escriba un numero: "))
N2 = int(input(f"Escriba un numero mayor o igual que {N1}: "))

if N2<=N1:
  print (f"Ingrese un numero mayor o igual que {N1}")
else:
  for i in range (N1, N2+1):
    if i%2 == 0: 
      print (f"El numero {i} par")
    else: 
      print (f"El numero {i} impar")

Escriba un numero: 8
Escriba un numero mayor o igual que 8: 9
El numero 8 par
El numero 9 impar


In [ ]:
# Identificar pares

N1 = int(input("Escriba un numero: "))

for i in range (1, N1+1):
  if i%2 == 0: 
    print (f"El numero {i} par")

Escriba un numero: 10
El numero 2 par
El numero 4 par
El numero 6 par
El numero 8 par
El numero 10 par


In [ ]:
# Identificar impares

N1 = int(input("Escriba un numero: "))

for i in range (1, N1+1):
  if i%2 == 0: 
    continue # SALTA DIRECTO AL ELSE
    print (f"El numero {i} par")
  else: 
    print (f"El numero {i} impar")

Escriba un numero: 10
El numero 1 impar
El numero 3 impar
El numero 5 impar
El numero 7 impar
El numero 9 impar


In [ ]:
# Identificar pares

N1 = int(input("Escriba un numero: "))

for i in range (1, N1+1):
  if i%2 == 0: 
    break #Rompe, sale del ciclo
    print (f"El numero {i} par")
  else: 
    print (f"El numero {i} impar")

Escriba un numero: 10
El numero 1 impar


In [ ]:
#Seleccionar los impares y romper cuando encuentre un numero divisible por 6

N = int(input("Ingrese un número: "))

for i in range (1, N):
  if (i%2==0):
    continue
    print (i)
  else: 
    print (i)
    if ((i+1)%6 == 0):
      break

Ingrese un número: 12
1
3
5


**12. Metodos** 

Lower: Convierte caracteres en minusculas

Upper: Convierte caracteres en mayusculas

Swapcase; Convierte los caracteres de may a min y viceversa

Count: Cuenta los elementos seleccionados

Replace: Remplaza un elemento por otro

Capitalize: Convierte el primer en Mayusculas y todas las demás en minusculas

Find: Enumera los carateres que no fueron seleccionados

In [ ]:
Cadena = "cURSO DE pYTHON"

print ("Lower: ", Cadena.lower())
print ("Upper: ", Cadena.upper())
print ("Swapcase: ", Cadena.swapcase())
print ("Count: ", Cadena.count("O"))
print ("Replace: ", Cadena.replace("pYTHON","Java"))
print ("Capitalize: ", Cadena.capitalize())
print ("Find: ", Cadena.find("p"))#Cuenta espacios y lentras que hay antes del dato seleccionado


Lower:  curso de python
Upper:  CURSO DE PYTHON
Swapcase:  Curso de Python
Count:  2
Replace:  cURSO DE Java
Capitalize:  Curso de python
Find:  9


In [ ]:
lista = [2,20,7,8,14,8]

print ("Valor máximo de la lista: ", max(lista))
print ("Longitud de la lista: ", len(lista))

lista.append(100)
print ("Se le agrega 100 a la lista", lista)

count = lista.count(8)
print ("Cuantas veces se repite el numero 8: ", count)

lista.sort()
print ("lista de forma ordenada: ", lista)

lista.reverse()
print ("lista invertida: ", lista)


Valor máximo de la lista:  20
Longitud de la lista:  6
Se le agrega 100 a la lista [2, 20, 7, 8, 14, 8, 100]
Cuantas veces se repite el numero 8:  2
lista de forma ordenada:  [2, 7, 8, 8, 14, 20, 100]
lista invertida:  [100, 20, 14, 8, 8, 7, 2]


**13. Funciones** 


In [ ]:
# Hallar el primerdio de 3 notas

def promedio (n1, n2, n3):
  return (n1+n2+n3)/3

N1 = float(input('Ingrese la nota 1: '))
N2 = float(input('Ingrese la nota 2: '))
N3 = float(input('Ingrese la nota 3: '))

print ("El primedio es: ", promedio (N1, N2, N3))

Ingrese la nota 1: 6
Ingrese la nota 2: 8
Ingrese la nota 3: 9
El primedio es:  7.666666666666667


In [ ]:
# Tabla de Multiplicar

def tabla (n):
  for i in range(1, 11):
    print (f"{n} x {i} = ", n*i)

N1 = int(input('Ingrese un numero: '))

print (tabla (N1))

Ingrese un numero: 6
6 x 1 =  6
6 x 2 =  12
6 x 3 =  18
6 x 4 =  24
6 x 5 =  30
6 x 6 =  36
6 x 7 =  42
6 x 8 =  48
6 x 9 =  54
6 x 10 =  60
None


In [ ]:
# Separar una lista en pares e impares

ejemplo = [1,4,8,7,2,9,12,21]

def separar (lista):
  lista.sort()
  par = []
  impar = []

  for i in lista:
    if i%2 == 0:
      par.append(i)
    else:
      impar.append(i)
  return par, impar

par, impar = separar(ejemplo)
print ("Los elementos pares son: ", par)
print ("Los elementos impares son: ", impar)

Los elementos pares son:  [2, 4, 8, 12]
Los elementos impares son:  [1, 7, 9, 21]


**14. Tuplas** 

Estructura de datos conformada por elementos de distinto tipo. Son INMUTABLES, se encierran en parentesis y sus elementos se separan por comas.

In [ ]:
a = 10
b = 5

# Intercambiar las variables

(a,b) = (b,a)
print (b)

10


In [ ]:
ejemplo = (35, "python", 4.6)
print (ejemplo)
print (ejemplo[1])

(35, 'python', 4.6)
python


In [ ]:
# Convertir una tupla a una lista

a = (4,6,9,"Hola",6,19.8)
lista = list(a)
print (lista)

tupla = tuple(lista)
print (tupla)

# Medir la longitud de una tupla

b = (4,5,6,3,5)
print (len(b))

# Entregar el Valor máximo de una Tupla

print (max (b))
print (min(b))

[4, 6, 9, 'Hola', 6, 19.8]
(4, 6, 9, 'Hola', 6, 19.8)
5
6
3


**15. Sets** 

También conocidos como conjuntos de datos para almacenar cualquier tipo de información


In [ ]:
set = {2,3,4}

# Agregar un valor a un set
set.add(5)
set.add(7)
set.add(1) #A diferencia de los demás, lo agrega al inicio respetando su orden
set.add('a')
print (set)


{1, 2, 3, 4, 5, 'a', 7}


**16. Diccionarios** 

Estructuras de datos consistentes en listas de pares de variables. Cada par tiene un elemento llamado clave (key) que se puede ser cualquier tipo y otro elemento llamado valor que también puede ser de cualquier tipo.

In [ ]:
edades = {'David':30, 'Carlos':60, 'Victor':24, 'Hugo':55}
print (edades)
print (edades['David'])
edades['Victor'] = 63
print (edades['Victor'])

for i in edades:
  print (i, edades[i])

{'David': 30, 'Carlos': 60, 'Victor': 24, 'Hugo': 55}
30
63
David 30
Carlos 60
Victor 63
Hugo 55


In [ ]:
# Diccionario con Funciones

notas = {'David': 85, 'Carlos':60, 'Victor':98, 'Andrea':60}

print(str(notas))
print(type(notas))
#print(notas.clear())

notas2 = notas.copy()
print (notas2)

{'David': 85, 'Carlos': 60, 'Victor': 98, 'Andrea': 60}
<class 'dict'>
{'David': 85, 'Carlos': 60, 'Victor': 98, 'Andrea': 60}


In [ ]:
notas = dict.fromkeys(['David', 'Carlos', 'Victor', 'Andrea'], 100)
print(notas)

valor = notas.get('David')
print (valor)

items = notas.items()
print (items)

keys = notas.keys()
print (keys)

value = notas.values()
print (value)

Victor = notas.pop('Andrea')
print (Victor)
print (notas)

dic1 = {'a':1, 'b':2, 'c':3, 'd':4}
dic2 = {'d':5, 'e':6, 'f':7, 'g':8}
dic1.update(dic2)
print (dic1)




{'David': 100, 'Carlos': 100, 'Victor': 100, 'Andrea': 100}
100
dict_items([('David', 100), ('Carlos', 100), ('Victor', 100), ('Andrea', 100)])
dict_keys(['David', 'Carlos', 'Victor', 'Andrea'])
dict_values([100, 100, 100, 100])
100
{'David': 100, 'Carlos': 100, 'Victor': 100}
{'a': 1, 'b': 2, 'c': 3, 'd': 5, 'e': 6, 'f': 7, 'g': 8}


**17.   Indices** 

In [ ]:
curso = 'Constitucionalmente'

print (curso[2])
print (curso[-5])
print (curso[3:10])
print (curso[:10])
print (curso[10:])

lista = list(curso)
print (lista)
print (lista.index('i'))

n
m
stituci
Constituci
onalmente
['C', 'o', 'n', 's', 't', 'i', 't', 'u', 'c', 'i', 'o', 'n', 'a', 'l', 'm', 'e', 'n', 't', 'e']
5


**17.   Palabras reservadas** 

DEL: Borra elementos dentro de una lista

IN: Verifica si un elemento es parte de una lista.

In [ ]:
curso = 'python'
lista = list(curso)
print (lista)

del lista [2]
print (lista)

print ('y' in curso)
print ('a' in curso)

['p', 'y', 't', 'h', 'o', 'n']
['p', 'y', 'h', 'o', 'n']
True
False


**18.   Vector** 

Conjunto de datos

In [ ]:
n = int(input('Ingrese el tamaño del arreglo: '))
m = int(input('Ingrese el numero de multiplos: '))
A = []

for i in range (0,n):
  A.append (i*m)

print (A)

Ingrese el tamaño del arreglo: 6
Ingrese el numero de multiplos: 3
[0, 3, 6, 9, 12, 15]


In [ ]:
#Imprimir por pantalla los numeros impares a 3

A = [1,2,5,7,8,9,10,11,12]
B = []

for i in A:
  if i>3 and i%2 != 0:
    B.append(i)

print (B)

[5, 7, 9, 11]


In [ ]:
# Calcular 10 numeros aleatorios

import random 

def vector_aleatorio(n):
  vector = [0]*n
  for i in range (n):
    vector [i] = random.randint(0,10)
  return vector

print ("Cuantos numeros aleatorios desea tener: ")
n = int(input())

aleatorio = vector_aleatorio(n)
print (aleatorio)

Cuantos numeros aleatorios desea tener: 
5
[7, 7, 3, 4, 1]


**19.  Vectores y Matrices**

In [ ]:
import numpy as np

enteros = np.array([0,1,2,3])
flotantes = np.array([0,1,2.3,3])

print (enteros)
print (flotantes)
print (enteros.astype(str))
print (enteros.astype(float))

a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
print (a+b)
print (a<b)
print (a[2])
print (a.max())
print (a.sum())

[0 1 2 3]
[0.  1.  2.3 3. ]
['0' '1' '2' '3']
[0. 1. 2. 3.]
[ 4  6  8 10]
[ True  True  True  True]
2
3
6


In [ ]:
import numpy as np

Vector = np.array([6,7,1,12,3])
Matriz1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Matriz2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print ('vector: ', Vector)
print ('Tamaño del vector: ', Vector.size)
print ('Matriz:\n', Matriz1)
print ('Tamaño de la Matriz: ', Matriz1.size)
print ('Suma Matrices:\n', Matriz1+Matriz2)

vector:  [ 6  7  1 12  3]
Tamaño del vector:  5
Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tamaño de la Matriz:  9
Suma Matrices:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**20.   Módulos** 

Coleccion de definiciones de variables, funciones y tipos (entre otras cosas) que pueden ser importadas para ser utilizadas desde cualquier programa.



In [ ]:
from math import pi

a = pi
print(a)

3.141592653589793


In [ ]:
from math import factorial

b = factorial(4)
print(b)

24


In [ ]:
from math import log

c = log(8,10)
print(c)

0.9030899869919434


In [ ]:
from random import choice

d = choice(['cara', 'cruz'])
print(d)

cruz


In [ ]:
from random import randrange

e = randrange(56)
print(e)

47


In [ ]:
from datetime import date

f = date(2021,12,28)
print(f)

2021-12-28


In [1]:
def Suma (Numero1, Numero2):
  Sum = Numero1 + Numero2
  return Sum

In [3]:
Suma(5,7)

12

In [4]:
Suma(-1,9)

8